### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Blakethepirate** [ManassehPierce/ExNihilo-PE#2]
Sir,i got all the files, installed the texturepack first, restarted blocklauncher and imported the .js files but still they all showed me errors will you please help me?

**Comment by Khristian-kun** [comment]
you have to use the main.js file, and right now maybe isnt working, so wait for the fixes

**Comment by Blakethepirate** [comment]
Ok ty khristian-kun. I will see about it.

**Comment by Taizgaming** [comment]
Could you send us the BlockLauncher error popup? We can further identify
the problem that way, thanks!

**Comment by CrazyWolfy23** [comment]
This should be fixed in the coming updates.

**Comment by ManassehPierce** [comment]
The reason there are errors is because each script calls a function from another file, and Blocklauncher doesn't support this. You would have to compile these in a certain order. I will upload a compiled script soon.

**Comment by ManassehPierce** [comment]
Here is a compiled script, I will update it every time a change is made. https://github.com/ManassehPierce/ExNihilo-PE/blob/master/compiled.js

**Comment by CrazyWolfy23** [comment]
@ManassehPierce I might be wrong, but ive seen it done before calling function between mods, it just requires a lot of work.

**Comment by Taizgaming** [comment]
I think BL interprets them by name, so naming the script which defines
functions/variables used in later scripts to something that would appear
higher which would allow BL to know what it is Like renaming scripts things
like 0_barrel.js and 1_curcible.js? (so BL reads the variables in before
theyre used)

**Comment by CrazyWolfy23** [comment]
Any ways, it'll just be easier combining all the scripts

**Comment by ManassehPierce** [comment]
Yes, blocklauncher has a way to call methods from other scripts, its not very practical. Also, on another note you can find an easy to use API here: https://github.com/sliceofcode/inform

**Comment by CrazyWolfy23** [comment]
yeah, lets just combine the project our selfs, it wouldn't be hard.
